### ISSUE TITLE
issue getting started

### ISSUE THREAD

**Issue by sw764206** [JordanMartin/harmonyhub-api#11]
Question on getting started for a novice here. I have basic experience installing node servers (using 2 for sonos (Sonos HTTP API) to make HTTP commands to the system). 

I ran npm install harmonyhub-api and ran the remote id command on my synology NAS which it did find the hub and ID. 

But do I need to run an npm start harmonyhub-api or npm start?   I tried both and I am getting an error 
argv /volume1/@appstore/Node.js_v6/usr/local/bin/node  /usr/local/bin/npm
node v 6.12.3 npm v3.10.10 
missing script start 

I downloaded the zip files from GIT and put them in
/volume1/homes/admin/harmony

**Comment by JordanMartin** [comment]
After running `npm install` you could find the id of your hub with the command : 
`node_modules/.bin/harmonyhub-remote-id <hub_ip>`

Then you could create a sample file to interract with your hub : 

**File `sample.js`**
```javascript
const HarmonyHub = require('harmonyhub-api').HarmonyHub;
const HUB_HOST = 'X.X.X.X';
const HUB_REMOTE_ID = 'XXXXXXX';
const hub = new HarmonyHub(HUB_HOST, HUB_REMOTE_ID);

hub.connect()
    .then((config) => {
        console.log('Connected to the hub');

        console.log('\nActivities\n==========');
        config.activity.forEach(activity => {
            console.log(`${activity.label} (${activity.id})`);
        });

        console.log('\nDevices\n========');
        config.device.forEach(device => {
            console.log(`${device.label} (${device.id})`);
        });
    });
```` 

And excute with : `node sample.js`
