### ISSUE TITLE
VolumeUp increase too much the volume

### ISSUE THREAD

**Issue by Jean-PhilippeD** [JordanMartin/harmonyhub-api#13]
Hi,

When I increase the volume (or decrease) with this.sendCommand('VolumeUp", <device id>)
It increase/decrease on my Logitech Amp way too much. 
While when I use harmony app and I click on the volume Up button, it's ok, but with harmonyhub-api, it's like if I was clicking 3 or 4 times the button in the app.

**Comment by JordanMartin** [comment]
Hello, 

Try to use this method : 
```javascript
// 50 is in milliseconds
hub.holdCommand('LevelDown', device_id, 50);
```

**Comment by Jean-PhilippeD** [comment]
It works !

Thanks.

By the way, why simple sendCommand seems to send command by holding more than 50ms ?

**Comment by JordanMartin** [comment]
It's the default implementation of the logitech API. The `sendCommand` just request a `press` action to the hub there aren't specified duration.
