### ISSUE TITLE
How can I stop an activity ?

### ISSUE THREAD

**Issue by Jean-PhilippeD** [JordanMartin/harmonyhub-api#15]
Hello,
I'd like to find the way I can stop an activity, because once it's started, I can not start it anymore while it has not been stopped before.

**Comment by JordanMartin** [comment]
Hello, 

Look at the result of `hub.getActivities()`. There is a default activity named `PowerOff` with the id `-1`.
So just call `hub.startActivity('-1')` to power off the current activity.

**Comment by Jean-PhilippeD** [comment]
Nice, I will test it.
