### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by wayner9** [JordanMartin/harmonyhub-api#22]
Hi, I am trying to figure out how to use this api to start and stop activities.  When I try the following I get a "Cannot read property 'sendUTF' of null" error.   FYI I have enabled XMPP for this hub.

const HarmonyHub = require('harmonyhub-api').HarmonyHub;
const HUB_HOST = '192.168.1.204';
const HUB_REMOTE_ID = '7606469';
const hub = new HarmonyHub(HUB_HOST, HUB_REMOTE_ID);

hub.connect()
	.then(hub.startActivity('-1')
	);

I would also like to just turn off the hub from a HTTP POST.  Why doesn't the following work?
curl -X POST 192.168.1.204:8088 -H 'Accept: utf-8' -H 'Content-Type: application/json' -H 'Origin: http://sl.dhg.myharmony.com' -d '{"hubId": "7606469","timeout": 60,"hbus": {"cmd": "vnd.logitech.harmony\/vnd.logitech.harmony.engine?startactivity","id": "0","params": {"async": "true","timestamp": 0,"args": {"rule": "start"},"activityId": "-1"}}}'

**Comment by wayner9** [comment]
Sorry but for some reason the insert code isn't working in my browser?

**Comment by JordanMartin** [comment]
You need tu use a callback like this :

```javascript 
hub.connect().then((config) => hub.startActivity('-1'));
```

**Comment by wayner9** [comment]
Thanks Jordan, that does the trick.  I am not familiar with callbacks.  

A couple more questions:
How do you get the program to terminate rather than wait around?

And could this be done straight from a HTTP POST, like my question above?  I would like to start/stop activities directly from my Control4 Home Automation software, and in that I can send HTTP POSTs.

**Comment by JordanMartin** [comment]
You can call `hub.disconnect()` to close the connection directly after your command : 
```javascript
hub.connect()
    .then((config) => hub.startActivity('-1'))
    .then(() => hub.disconnect())
```

This module is connecting the hub by websocket. It's not only a simple HTTP request.
I'm not sure my module is compatible "as is" with a browser (never tested)

I do not know Control4 Home Automation, but you have 2 solutions : 
- Run a HTTP server (like express) and expose some HTTP route that call the module
- Use another module or implement your solution : take a look at this documentation https://github.com/NovaGL/diy-harmonyhub

**Comment by wayner9** [comment]
Thanks Jordan - I was going to do what you suggested and use CGI through Apache to handle the request with something like http://mywebserver/cgi-bin/startactivity?ip=192.168.1.204&remoteid=734123&activity=-1

I have done that before with Apache but not with NodeJS.

I have seen that NovaGL repository.  I used that to fashion the URL called in the curl statement in the first post of this thread.  Thanks for your help!
