### ISSUE TITLE
Catch press of an unused remote control button

### ISSUE THREAD

**Issue by JensC** [JordanMartin/harmonyhub-api#23]
Hi,

I have a question. Is it possible to use a button that has no functionality in an activity e.g. "Listen to Music" and catch this through the websocket api. I think with some kind of polling? Maybe I need to customize a button first? Like in https://support.myharmony.com/en-gb/customizing-physical-buttons-on-your-remote

Thanks for any hint
Jens

**Comment by JordanMartin** [comment]
Hello, 

All event are available with : 
```javascript
hub.on('message', data => console.log(data));
```

To my knowledge, only start/stop an activity emits an event on the websocket connection.
