### ISSUE TITLE
Newbie Help Please

### ISSUE THREAD

**Issue by gambler2841** [JordanMartin/harmonyhub-api#26]
Hi! I'm a newbie. I was able to follow along to find the hub. I'm not sure what exactly I'm supposed to do to connect to the hub. 

![image](https://user-images.githubusercontent.com/15316131/182982674-c753ffda-32c1-41c0-9a2e-7c09df4f11a8.png)

**Comment by JordanMartin** [comment]
Hello,

 All steps are describe in the readme. You should pick up the snippet, add the host and the remonte id to open the connection with the hub
