### ISSUE TITLE
Not able to get the Hub ID

### ISSUE THREAD

**Issue by jpoeppelman1** [JordanMartin/harmonyhub-api#5]
I'm trying to get the Hub ID, but it fails.  

C:\Users\jlpoeppe\AppData\Roaming\npm\node_modules\.bin>node harmonyhub-remote-id 192.168.1.110
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module 'C:\Users\jlpoeppe\AppData\Roaming\npm\node_modules\.bin\harmonyhub-remote-id'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:527:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

C:\Users\jlpoeppe\AppData\Roaming\npm\node_modules\.bin>

**Comment by NicolaNauwynck** [comment]
Change the Origin to http://sl.dhg.myharmony.com, that worked for me

**Comment by JordanMartin** [comment]
Hello thanks @NicolaNauwynck for your contribution.
Logitech has changed some api endpoint. I patch (3fdb8db)  the package in version 1.0.8 and the corresponding doc.
Please let me now if it's ok now.
