### ISSUE TITLE
resolve with config on connect

### ISSUE THREAD

**Issue by MartinMuzatko** [JordanMartin/harmonyhub-api#7]
Your example in the readme says you should await the promise using `then` to retrieve the config

``` js
const hub = new HarmonyHub(HUB_HOST, HUB_REMOTE_ID);

hub.connect()
    .then((config) => {
        console.log('Connected to the hub');
```

But this is wrong.
You only get the config on the `connected` event.

https://github.com/JordanMartin/harmonyhub-api/blob/master/src/HarmonyHub.ts#L63

Please resolve the promise with the config object.

**Comment by JordanMartin** [comment]
Thanks for the report, it is now fixed.
