### ISSUE TITLE
Get error on retrieving the remote id of the hub

### ISSUE THREAD

**Issue by vreesie18** [JordanMartin/harmonyhub-api#8]
My command:  node_modules/.bin/harmonyhub-remote-id 192.168.1.x

Found Logitech Harmony Hub
---------------------------
Request to the hub failed: Cannot read property 'friendlyName' of undefined
The host/ip may be incorrect or the hub is not power up

TypeError: Cannot read property 'friendlyName' of undefined
    at /root/node_modules/harmonyhub-api/dist/get-remote-id.js:17:34
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by coin9176** [comment]
The same for me.
Have you an issue ?
Without the hub ID it is impossible to do nothing

**Comment by NicolaNauwynck** [comment]
Change the Origin to http://sl.dhg.myharmony.com with the http post request, that worked for me

**Comment by vreesie18** [comment]
Please explain...

**Comment by NicolaNauwynck** [comment]
![Screenshot_86](https://user-images.githubusercontent.com/617804/78503391-8cc03e00-7766-11ea-8904-900f7a6e1e1c.png)
![Screenshot_87](https://user-images.githubusercontent.com/617804/78503392-8d58d480-7766-11ea-99b2-a56ad19ed6f7.png)

I used postman to get the device ID, in the readme it is described but the origin URL in the description is wrong. I used http://sl.dhg.myharmony.com as the origing URL.

I am now trying to figure out if the event listener works, so far no result :(

**Comment by NicolaNauwynck** [comment]
@vreesie18 did this work for you?

**Comment by coin9176** [comment]
Hi,
I replace Origin': 'http://localhost.nebula.myharmony.com' by 'Origin': 'http://sl.dhg.myharmony.com'
in /node_modules/harmonyhub-api/dist/get-remote-id.js and run it but always the same error (TypeError: Cannot read property 'friendlyName' of undefined)
Thanks for your help

**Comment by JordanMartin** [comment]
It's now patched (3fdb8db). The package is now in version 1.0.8.
Please let me now if it's ok now.

**Comment by coin9176** [comment]
Thanks very much, it's ok now !
