### ISSUE TITLE
Is it possible to listen for command inputs?

### ISSUE THREAD

**Issue by NicolaNauwynck** [JordanMartin/harmonyhub-api#9]
It seems like that I can only track activity events with
`            
            hub.on('message', function(result) {
                console.log(result);
            });
`

How can I track commands like when I have pushed on the menu button on the remote?

I want to bind some of the buttons of the remote to control lights.

Based on the documentation I know how to get the commands and trigger a command but can I also listen for commands?

**Comment by JordanMartin** [comment]
Hello, 
I don't think it is possible and never seen another package doing so.
But i'm interested if you find a way.

**Comment by NicolaNauwynck** [comment]
Found a different way to do this based on https://www.youtube.com/watch?v=-Wv4vGG86OQ

Configured Tasker to send HTTP request to my node server when a button is pressed that is on the local network. I configured Tasker on ShieldTV, this device was already part of my media setup.

**Comment by JordanMartin** [comment]
Thanks for the tip. Too bad it is so difficult to meet this simple need.
